name: "AHP"
description: "Aplicacion de apoyo de toma de decisiones implementando el Algoritmo AHP"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  http: 
  syncfusion_flutter_charts: ^27.1.52
  shared_preferences: ^2.0.13  
 # flutter_localizations:
   # sdk: flutter
  #intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

